const FILMS = [
  {
    "id": "ideas-of-order",
    "title": "Ideas of Order",
    "rating": 5.0,
    "original_title": "",
    "release_year": 2026,
    "premiere": "",
    "category": "NEW DOCS",
    "description": "A collision between the macro-collapse of ecosystems and the minutiae of cellular colonies, in a story about entropy, unrestrained growth, waltzing mice, earlier-onset cancers, programmed death, and the bacteria that made Earth rich in oxygen—opening up space for life today.",
    "screening_date": "Friday, April 17",
    "screening_start_time": "4:00 PM",
    "screening_end_time": "6:00 PM",
    "venue": "Cinema 1",
    "schedule_color": "blue"
  },
  {
    "id": "joybubbles",
    "title": "Joybubbles",
    "rating": 5.0,
    "original_title": "",
    "release_year": 2026,
    "premiere": "",
    "category": "NEW DOCS",
    "description": "A boy discovers he can control the global telephone system by whistling a magic tone. Born blind and yearning for connection, his early obsession with the telephone sparks a subculture that shapes the future of hacking and technology.",
    "screening_date": "Saturday, April 18",
    "screening_start_time": "11:30 AM",
    "screening_end_time": "1:30 PM",
    "venue": "Cinema 4",
    "schedule_color": "blue"
  },
  {
    "id": "kikuyu-land",
    "title": "Kikuyu Land",
    "rating": 5.0,
    "original_title": "",
    "release_year": 2026,
    "premiere": "",
    "category": "Invited",
    "description": "In Kenya's tea highlands, one man's claim to his family's stolen land sets Mr. Mungai against a multinational giant. His fight draws a local news producer into a battle that exposes buried histories, family secrets, and the unfinished business of colonial power.",
    "screening_date": "Friday, April 17",
    "screening_start_time": "11:00 AM",
    "screening_end_time": "1:00 PM",
    "venue": "Fletcher",
    "schedule_color": "yellow"
  },
  {
    "id": "nuisance-bear",
    "title": "Nuisance Bear",
    "rating": 5.0,
    "original_title": "",
    "release_year": 2026,
    "premiere": "",
    "category": "Invited",
    "description": "A polar bear is forced to navigate a human world of tourists, wildlife officers, and hunters as its ancient migration collides with modern life. When a sacred predator is branded a nuisance, it becomes unclear who truly belongs in this shared landscape.",
    "screening_date": "Saturday, April 18",
    "screening_start_time": "5:00 PM",
    "screening_end_time": "7:00 PM",
    "venue": "Fletcher",
    "schedule_color": "yellow"
  },
  {
    "id": "seized",
    "title": "Seized",
    "rating": 5.0,
    "original_title": "",
    "release_year": 2026,
    "premiere": "",
    "category": "NEW DOCS",
    "description": "When the small town of Marion, Kansas, is thrust into the international spotlight after a police raid on the Marion County Record and the death of its 98-year-old co-owner, a fierce debate ignites about the abuse of power, journalistic ethics, local journalism, and the United States Constitution.",
    "screening_date": "Thursday, April 16",
    "screening_start_time": "10:30 AM",
    "screening_end_time": "12:30 PM",
    "venue": "Fletcher",
    "schedule_color": "blue"
  },
  {
    "id": "militantropos",
    "title": "Militantropos",
    "rating": 4.5,
    "original_title": "",
    "release_year": 2025,
    "premiere": "North American Premiere",
    "category": "NEW DOCS",
    "description": "Militantropos captures the human condition through the fractured realities of the Russian invasion of Ukraine. The film pieces together everyday lives transformed by war—those who flee, those who lose everything, and those who stay to resist and fight—tracing both the instinct to survive and the need for closeness.",
    "screening_date": "Saturday, April 18",
    "screening_start_time": "5:30 PM",
    "screening_end_time": "7:30 PM",
    "venue": "Cinema 4",
    "schedule_color": "blue"
  },
  {
    "id": "no-mean-city",
    "title": "No Mean City",
    "rating": 4.5,
    "original_title": "",
    "release_year": 2025,
    "premiere": "",
    "category": "NEW DOCS",
    "description": "Two workmen and an apprentice drive through Belfast at night, replacing old sodium streetlights with LED. Beneath their glow, the city grapples with change, as progress marches on.",
    "screening_date": "Thursday, April 16",
    "screening_start_time": "7:30 PM",
    "screening_end_time": "9:30 PM",
    "venue": "Cinema 1",
    "schedule_color": "blue"
  },
  {
    "id": "still-standing",
    "title": "Still Standing",
    "rating": 4.5,
    "original_title": "",
    "release_year": 2025,
    "premiere": "",
    "category": "NEW DOCS",
    "description": "After the Los Angeles wildfires leave thousands of homes contaminated with toxic ash, residents face an impossible choice: should they risk their health to return home?",
    "screening_date": "Saturday, April 18",
    "screening_start_time": "4:00 PM",
    "screening_end_time": "6:00 PM",
    "venue": "Cinema 1",
    "schedule_color": "blue"
  },
  {
    "id": "the-last-first-winter-k2",
    "title": "The Last First: Winter K2",
    "rating": 4.5,
    "original_title": "",
    "release_year": 2025,
    "premiere": "",
    "category": "Invited",
    "description": "The Last First: Winter K2 takes us to the icy heights and unpredictable weather of K2 and reveals a surprising and layered story—one of strategy and determination, class and caste, money and power—all under life and death circumstances.",
    "screening_date": "Friday, April 17",
    "screening_start_time": "8:00 PM",
    "screening_end_time": "10:00 PM",
    "venue": "Fletcher",
    "schedule_color": "yellow"
  },
  {
    "id": "the-rehearsal",
    "title": "The Rehearsal",
    "rating": 4.5,
    "original_title": "",
    "release_year": 2025,
    "premiere": "",
    "category": "Thematic",
    "description": "The Rehearsal follows one man's journey to reduce the uncertainties of everyday life. With a construction crew, a legion of actors, and seemingly unlimited resources, Fielder helps ordinary people prepare for life's biggest moments by \"rehearsing\" them in carefully crafted simulations of his own design. In season two, the urgency of Fielder's project grows as he decides to put his resources toward an issue that affects us all.",
    "screening_date": "Saturday, April 18",
    "screening_start_time": "5:00 PM",
    "screening_end_time": "8:00 PM",
    "venue": "Cinema 2",
    "schedule_color": "blue"
  },
  {
    "id": "the-way-i-see-it",
    "title": "The Way I See It",
    "rating": 4.5,
    "original_title": "",
    "release_year": 2020,
    "premiere": "",
    "category": "Tribute",
    "description": "Pete Souza captures historic and intimate moments as a photographer for President Barack Obama and President Ronald Reagan. The Way I See It traces Souza's journey from a man with top secret clearance and total access to the President, whose job description meant he was required to be invisible, to a man who has turned his focus on the present day and who uses his art as commentary to help us understand where we are now as a country and what we might be missing.",
    "screening_date": "Friday, April 17",
    "screening_start_time": "2:00 PM",
    "screening_end_time": "4:00 PM",
    "venue": "Fletcher",
    "schedule_color": "tan"
  },
  {
    "id": "true-north",
    "title": "True North",
    "rating": 4.5,
    "original_title": "",
    "release_year": 2025,
    "premiere": "",
    "category": "NEW DOCS",
    "description": "Through never-before-seen compelling historical footage and the voices of those who lived through the tumultuous period of 1960s Montréal, True North uses a bold cinematic aesthetic that centers the power of memory and archive to expose the pivotal events of a moment that impacted the global movement for Black liberation.",
    "screening_date": "Saturday, April 18",
    "screening_start_time": "4:30 PM",
    "screening_end_time": "6:30 PM",
    "venue": "Cinema 3",
    "schedule_color": "blue"
  },
  {
    "id": "a-child-of-my-own",
    "title": "A Child of My Own",
    "rating": 4.0,
    "original_title": "",
    "release_year": 2026,
    "premiere": "North American Premiere",
    "category": "Invited",
    "description": "The profound desire to become a mother and the pressure from her surroundings drive Alejandra to fake a pregnancy. What begins as a simple lie turns into a complex charade to sustain for months before a hopeful husband and family. It unleashes a media scandal that won't allow her to continue lying.",
    "screening_date": "Sunday, April 19",
    "screening_start_time": "1:30 PM",
    "screening_end_time": "3:30 PM",
    "venue": "Cinema 1",
    "schedule_color": "yellow"
  },
  {
    "id": "benita",
    "title": "BENITA",
    "rating": 4.0,
    "original_title": "",
    "release_year": 2025,
    "premiere": "",
    "category": "Invited",
    "description": "In this deeply intimate and haunting documentary, Alan Berliner posthumously collaborates with his friend and colleague, experimental New York City filmmaker Benita Raphan, who died by suicide during the COVID-19 pandemic. The film is an unflinching, lyrical, and ultimately moving study of an artist's mind, offering profound insights into the intersections of mental health, creativity, loneliness, and human resilience.",
    "screening_date": "Thursday, April 16",
    "screening_start_time": "5:00 PM",
    "screening_end_time": "7:00 PM",
    "venue": "Cinema 3",
    "schedule_color": "blue"
  },
  {
    "id": "concepto-de-ciudadano",
    "title": "Concepto de Ciudadano",
    "rating": 4.0,
    "original_title": "",
    "release_year": 2024,
    "premiere": "",
    "category": "Thematic",
    "description": "Inside the installations of a deportation center, a Mexican immigrant hears the innocent question: Where are you from? His answer determines which side of the Mexican American border he belongs to. Years after proving he is an American citizen, the fear of losing the life he built in the streets of L.A. makes him hide parts of his life story.",
    "screening_date": "Sunday, April 19",
    "screening_start_time": "10:00 AM",
    "screening_end_time": "12:00 PM",
    "venue": "Cinema 1",
    "schedule_color": "green"
  },
  {
    "id": "cookie-queens",
    "title": "Cookie Queens",
    "rating": 4.0,
    "original_title": "",
    "release_year": 2025,
    "premiere": "",
    "category": "Invited",
    "description": "It's Girl Scout Cookie season, and four tenacious girls strive to be a top-selling \"Cookie Queen,\" navigating an $800 million business in which innocence and ambition collide.",
    "screening_date": "Saturday, April 18",
    "screening_start_time": "2:00 PM",
    "screening_end_time": "4:00 PM",
    "venue": "Fletcher",
    "schedule_color": "yellow"
  },
  {
    "id": "jaripeo",
    "title": "Jaripeo",
    "rating": 4.0,
    "original_title": "",
    "release_year": 2026,
    "premiere": "",
    "category": "NEW DOCS",
    "description": "Jaripeo journeys to Michoacán's hypermasculine rodeos. What starts as a celebration of tradition descends into the subconscious of memory, queer desire, and longing—a reckoning with the wounds and beauty of a home left behind.",
    "screening_date": "Saturday, April 18",
    "screening_start_time": "2:30 PM",
    "screening_end_time": "4:30 PM",
    "venue": "Cinema 4",
    "schedule_color": "blue"
  },
  {
    "id": "mother-lidia",
    "title": "Mother Lidia",
    "rating": 4.0,
    "original_title": "Mamita Lidia",
    "release_year": 2025,
    "premiere": "US Premiere",
    "category": "NEW DOCS",
    "description": "Mother Lidia is an immersive and unsettling portrait of Lidia Fuentes, a Chilean healer with a divine gift for breaking curses. In her home, we see her receiving patients seeking to be cured of ailments with dark origins. Between exorcisms and moments of daily life, a universe is revealed where a complex balance exists between the magical and the earthly.",
    "screening_date": "Friday, April 17",
    "screening_start_time": "10:00 AM",
    "screening_end_time": "12:00 PM",
    "venue": "Cinema 1",
    "schedule_color": "blue"
  },
  {
    "id": "soul-patrol",
    "title": "Soul Patrol",
    "rating": 4.0,
    "original_title": "",
    "release_year": 2026,
    "premiere": "",
    "category": "NEW DOCS",
    "description": "From deep behind enemy lines, a hidden chapter of American military history is uncovered, prompting the question of whether reckoning with the past can bring peace to those who lived it. The Vietnam War's first Black special operations team reunites to tell their story.",
    "screening_date": "Saturday, April 18",
    "screening_start_time": "11:00 AM",
    "screening_end_time": "1:00 PM",
    "venue": "Fletcher",
    "schedule_color": "yellow"
  },
  {
    "id": "the-cloud-factory",
    "title": "The Cloud Factory",
    "rating": 4.0,
    "original_title": "Wolkenfabrik",
    "release_year": 2025,
    "premiere": "US Premiere",
    "category": "NEW DOCS",
    "description": "\"The Cloud Factory\" is a cinematic exploration of the sky above the Rhenish coal mining region, where emission-enriched air masses ascend into the atmosphere to transform the climate. What can these human-made clouds tell us about our future? And what kind of castles can we build in this air?",
    "screening_date": "Saturday, April 18",
    "screening_start_time": "4:00 PM",
    "screening_end_time": "6:00 PM",
    "venue": "Cinema 1",
    "schedule_color": "blue"
  },
  {
    "id": "the-cool-world",
    "title": "The Cool World",
    "rating": 4.0,
    "original_title": "",
    "release_year": 1963,
    "premiere": "",
    "category": "Thematic",
    "description": "Shirley Clarke's vérité-style portrait follows Duke, a fifteen-year-old member of a Harlem youth gang, the Royal Pythons. Made in 1963 and produced by Frederick Wiseman, the narrative features a cast of non-actors filmed on location.",
    "screening_date": "Friday, April 17",
    "screening_start_time": "11:00 AM",
    "screening_end_time": "1:00 PM",
    "venue": "Cinema 2",
    "schedule_color": "green"
  },
  {
    "id": "the-lake",
    "title": "The Lake",
    "rating": 4.0,
    "original_title": "",
    "release_year": 2025,
    "premiere": "",
    "category": "NEW DOCS",
    "description": "An environmental nuclear bomb looms in Utah. Two intrepid scientists and a political insider race the clock to save their home from unprecedented catastrophe.",
    "screening_date": "Friday, April 17",
    "screening_start_time": "1:30 PM",
    "screening_end_time": "3:30 PM",
    "venue": "Cinema 3",
    "schedule_color": "blue"
  },
  {
    "id": "the-oldest-person-in-the-world",
    "title": "The Oldest Person in the World",
    "rating": 4.0,
    "original_title": "",
    "release_year": 2026,
    "premiere": "",
    "category": "Invited",
    "description": "A decade-long global odyssey chronicles the ever-changing record holders of the title of oldest person alive. What begins as a portrait of longevity becomes a poignant meditation on the passage of time, the randomness of fate and the joy and profound human experience of being alive.",
    "screening_date": "Thursday, April 16",
    "screening_start_time": "8:00 PM",
    "screening_end_time": "10:00 PM",
    "venue": "Fletcher",
    "schedule_color": "yellow"
  },
  {
    "id": "to-hold-a-mountain",
    "title": "To Hold a Mountain",
    "rating": 4.0,
    "original_title": "",
    "release_year": 2026,
    "premiere": "",
    "category": "NEW DOCS",
    "description": "In the remote highlands of Montenegro, a shepherd mother and daughter proudly defend their ancestral mountain from the threat of becoming a NATO military training ground, stirring memories of the violence that shattered their family.",
    "screening_date": "Thursday, April 16",
    "screening_start_time": "4:30 PM",
    "screening_end_time": "6:30 PM",
    "venue": "Fletcher",
    "schedule_color": "blue"
  },
  {
    "id": "trapped",
    "title": "Trapped",
    "rating": 4.0,
    "original_title": "",
    "release_year": 2016,
    "premiere": "",
    "category": "Tribute",
    "description": "The story of reproductive health care providers in the South struggling against controversial new regulations.",
    "screening_date": "Saturday, April 18",
    "screening_start_time": "10:00 AM",
    "screening_end_time": "12:00 PM",
    "venue": "Cinema 3",
    "schedule_color": "tan"
  },
  {
    "id": "when-a-witness-recants",
    "title": "When A Witness Recants",
    "rating": 4.0,
    "original_title": "",
    "release_year": 2026,
    "premiere": "",
    "category": "Tribute",
    "description": "In 1983, author Ta-Nehisi Coates learned that a 14-year-old boy was murdered in his Baltimore middle school. Upon revisiting the case, he uncovers the truth: three innocent teenagers were wrongfully convicted and spent 36 years in prison—creating a lasting impact on the accused, the witnesses, and their community.",
    "screening_date": "Saturday, April 18",
    "screening_start_time": "8:00 PM",
    "screening_end_time": "10:00 PM",
    "venue": "Fletcher",
    "schedule_color": "tan"
  },
  {
    "id": "luther-never-too-much",
    "title": "Luther: Never Too Much",
    "rating": 3.5,
    "original_title": "",
    "release_year": 2024,
    "premiere": "",
    "category": "Tribute",
    "description": "Luther: Never Too Much chronicles the story of a vocal virtuoso. Using a wealth of rarely seen archives, Luther Vandross tells his own story with assistance from his closest friends and musical collaborators including Mariah Carey, Dionne Warwick, Valerie Simpson, and Roberta Flack. The film relives the many stunning moments of Luther's musical career, while exploring his unrequited love life, health struggles, and a lifelong battle to earn the respect his music deserved.",
    "screening_date": "Friday, April 17",
    "screening_start_time": "8:30 PM",
    "screening_end_time": "10:30 PM",
    "venue": "Cinema 4",
    "schedule_color": "yellow"
  },
  {
    "id": "shifting-baselines",
    "title": "Shifting Baselines",
    "rating": 3.5,
    "original_title": "",
    "release_year": 2025,
    "premiere": "",
    "category": "Invited",
    "description": "Where the Rio Grande meets the sea, the rockets of SpaceX are launched; astronomers gaze skyward, hawkers shill their wares and environmentalists survey the damage. Welcome to Boca Chica, USA.",
    "screening_date": "Thursday, April 16",
    "screening_start_time": "10:00 AM",
    "screening_end_time": "12:00 PM",
    "venue": "Cinema 1",
    "schedule_color": "yellow"
  },
  {
    "id": "we-were-the-scenery",
    "title": "We Were The Scenery",
    "rating": 3.5,
    "original_title": "",
    "release_year": 2025,
    "premiere": "",
    "category": "Thematic",
    "description": "The story of Hoa Thi Le and Hue Nguyen Che, who, in 1975, after fleeing the Vietnam War by boat and docking in the Philippines, were utilized as background extras in the filming of Apocalypse Now.",
    "screening_date": "Thursday, April 16",
    "screening_start_time": "1:00 PM",
    "screening_end_time": "3:00 PM",
    "venue": "Cinema 1",
    "schedule_color": "blue"
  },
  {
    "id": "a-fox-under-a-pink-moon",
    "title": "A Fox Under a Pink Moon",
    "rating": 3.0,
    "original_title": "",
    "release_year": 2025,
    "premiere": "US Premiere",
    "category": "NEW DOCS",
    "description": "A subtly textured self-portrait of Soraya—an Afghan free-spirited 16-year-old artist in Iran who has been trying for five years to make her way to Europe—who chillingly captures everything on her phone while pouring all her fears and worries into extraordinary works of art.",
    "screening_date": "Saturday, April 18",
    "screening_start_time": "10:00 AM",
    "screening_end_time": "12:00 PM",
    "venue": "Cinema 1",
    "schedule_color": "blue"
  },
  {
    "id": "ask-e-jean",
    "title": "Ask E. Jean",
    "rating": 3.0,
    "original_title": "",
    "release_year": 2025,
    "premiere": "",
    "category": "Invited",
    "description": "The thrilling and adventurous life of beloved advice columnist and gonzo journalist E. Jean Carroll, the only woman to beat Trump in court. Twice.",
    "screening_date": "Friday, April 17",
    "screening_start_time": "10:30 AM",
    "screening_end_time": "12:30 PM",
    "venue": "Cinema 3",
    "schedule_color": "yellow"
  },
  {
    "id": "baea",
    "title": "BAEA",
    "rating": 3.0,
    "original_title": "",
    "release_year": 2025,
    "premiere": "North American Premiere",
    "category": "NEW DOCS",
    "description": "In the dead of winter, at a wildlife rescue center on the pacific coast of so-called Canada, a team of rehabbers treat Bald Eagles suffering from lead poisoning so that they can be released back to their environment.",
    "screening_date": "Friday, April 17",
    "screening_start_time": "1:30 PM",
    "screening_end_time": "3:30 PM",
    "venue": "Cinema 3",
    "schedule_color": "blue"
  },
  {
    "id": "bushman",
    "title": "Bushman",
    "rating": 3.0,
    "original_title": "",
    "release_year": 1971,
    "premiere": "",
    "category": "Thematic",
    "description": "When Paul Okpokam arrived in the U.S. in 1968, David Schickele decided to make a film about his Nigerian friend's experience of coming to teach at San Francisco State College. Truth is stranger than fiction in Bushman, a rare sort of film portrait, part document, part imagined, and poetic in its approach to real events.",
    "screening_date": "Sunday, April 19",
    "screening_start_time": "10:00 AM",
    "screening_end_time": "12:00 PM",
    "venue": "Cinema 1",
    "schedule_color": "green"
  },
  {
    "id": "gatorville",
    "title": "Gatorville",
    "rating": 3.0,
    "original_title": "",
    "release_year": 2025,
    "premiere": "",
    "category": "NEW DOCS",
    "description": "As childhood memories are made and fade in the same instant, siblings Lily and Bodhi diverge at the dawn of life beyond their home, a Colorado alligator sanctuary. Their bond, forged by the exotic nature of their remote landscape, begins to change as Lily enters her teenage years. Bodhi contemplates friendship and family beyond his reptilian counterparts.",
    "screening_date": "Friday, April 17",
    "screening_start_time": "1:00 PM",
    "screening_end_time": "3:00 PM",
    "venue": "Cinema 1",
    "schedule_color": "blue"
  },
  {
    "id": "the-grandfather-puzzle",
    "title": "The Grandfather Puzzle",
    "rating": 3.0,
    "original_title": "",
    "release_year": 2026,
    "premiere": "World Premiere",
    "category": "NEW DOCS",
    "description": "When a puzzle-obsessed grandfather refuses to discuss his past, his granddaughter travels to photograph the Hungarian castle where he grew up and turn it into a puzzle. What starts as a simple mission becomes a deeper exploration of displacement and home.",
    "screening_date": "Friday, April 17",
    "screening_start_time": "1:00 PM",
    "screening_end_time": "3:00 PM",
    "venue": "Cinema 1",
    "schedule_color": "blue"
  },
  {
    "id": "the-great-experiment",
    "title": "The Great Experiment",
    "rating": 3.0,
    "original_title": "",
    "release_year": 2026,
    "premiere": "",
    "category": "NEW DOCS",
    "description": "The Great Experiment reflects on this nation once dubbed \"the last great experiment in democracy,\" by documenting one four-year period of political upheaval from 2017 to 2020 to create a deeply affecting portrait of our nation and its people.",
    "screening_date": "Saturday, April 18",
    "screening_start_time": "1:30 PM",
    "screening_end_time": "3:30 PM",
    "venue": "Cinema 3",
    "schedule_color": "blue"
  },
  {
    "id": "the-silence-of-pomegranates",
    "title": "The silence of pomegranates",
    "rating": 3.0,
    "original_title": "Il silenzio dei melograni",
    "release_year": 2025,
    "premiere": "North American Premiere",
    "category": "NEW DOCS",
    "description": "In a coastal town in Calabria, southern Italy, a woman who prefers to remain anonymous breaks the silence surrounding the issue of abortion in the region.",
    "screening_date": "Friday, April 17",
    "screening_start_time": "4:00 PM",
    "screening_end_time": "6:00 PM",
    "venue": "Cinema 1",
    "schedule_color": "blue"
  },
  {
    "id": "alone",
    "title": "Alone",
    "rating": null,
    "original_title": "",
    "release_year": 2017,
    "premiere": "",
    "category": "Thematic",
    "description": "This stirringly poetic documentary puts a human face on the ravages of the American carceral state as a conflicted young woman contemplates marrying her imprisoned boyfriend.",
    "screening_date": "Thursday, April 16",
    "screening_start_time": "4:00 PM",
    "screening_end_time": "6:00 PM",
    "venue": "Cinema 1",
    "schedule_color": "green"
  },
  {
    "id": "america",
    "title": "America",
    "rating": null,
    "original_title": "",
    "release_year": 2019,
    "premiere": "",
    "category": "Thematic",
    "description": "Inspired by the earliest surviving feature film with an all-Black cast and through a series of vignettes rooted in New Orleans, America challenges the idea of Black cinema as a wave or \"movement in time,\" proposing instead a continuous thread of achievement.",
    "screening_date": "Thursday, April 16",
    "screening_start_time": "4:00 PM",
    "screening_end_time": "6:00 PM",
    "venue": "Cinema 1",
    "schedule_color": "green"
  },
  {
    "id": "american-doctor",
    "title": "American Doctor",
    "rating": null,
    "original_title": "",
    "release_year": 2026,
    "premiere": "",
    "category": "NEW DOCS",
    "description": "When three American doctors–Palestinian, Jewish, and Zoroastrian–enter Gaza to save lives, they find themselves caught between medicine and politics, risking everything to expose the truth.",
    "screening_date": "Friday, April 17",
    "screening_start_time": "7:00 PM",
    "screening_end_time": "9:00 PM",
    "venue": "Cinema 1",
    "schedule_color": "blue"
  },
  {
    "id": "american-pachuco-the-legend-of-luis-valdez",
    "title": "American Pachuco: The Legend of Luis Valdez",
    "rating": null,
    "original_title": "",
    "release_year": 2026,
    "premiere": "",
    "category": "NEW DOCS",
    "description": "Against political resistance and industry skepticism, Luis Valdez pushes Chicano storytelling from the fields to the film screen with Zoot Suit and La Bamba, crafting iconic works that challenge, celebrate, and expand America's story.",
    "screening_date": "Saturday, April 18",
    "screening_start_time": "7:00 PM",
    "screening_end_time": "9:00 PM",
    "venue": "Cinema 1",
    "schedule_color": "blue"
  },
  {
    "id": "an-open-field",
    "title": "an open field",
    "rating": null,
    "original_title": "",
    "release_year": 2025,
    "premiere": "North American Premiere",
    "category": "NEW DOCS",
    "description": "One of two Boeing airplane crashes six years ago, caused by a software failure, killed 157 people, including my brother Max. I travel with my father to the crash site in search of something tangible in our grief. Here, we met people for whom mourning is a profound part of their culture—a humanity contrasting with the manufacturer's calculated stance.",
    "screening_date": "Saturday, April 18",
    "screening_start_time": "4:00 PM",
    "screening_end_time": "6:00 PM",
    "venue": "Cinema 1",
    "schedule_color": "blue"
  },
  {
    "id": "barbara-forever",
    "title": "Barbara Forever",
    "rating": null,
    "original_title": "",
    "release_year": 2026,
    "premiere": "",
    "category": "NEW DOCS",
    "description": "An archive-driven exploration of the life, work, and legacy of iconic, pioneering lesbian filmmaker Barbara Hammer.",
    "screening_date": "Friday, April 17",
    "screening_start_time": "7:30 PM",
    "screening_end_time": "9:30 PM",
    "venue": "Cinema 3",
    "schedule_color": "blue"
  },
  {
    "id": "bisbee-17-short-film-no-2-of-6",
    "title": "BISBEE '17 SHORT FILM (no. 2 of 6)",
    "rating": null,
    "original_title": "",
    "release_year": 2019,
    "premiere": "",
    "category": "Thematic",
    "description": "A short film from unused material from BISBEE '17 that deconstructs the circumstances around the two deaths on the day of the Bisbee Deportation in 1917.",
    "screening_date": "Friday, April 17",
    "screening_start_time": "4:30 PM",
    "screening_end_time": "6:30 PM",
    "venue": "Cinema 3",
    "schedule_color": "blue"
  },
  {
    "id": "bree-wayy-promise-witness-remembrance",
    "title": "Bree Wayy: Promise Witness Remembrance",
    "rating": null,
    "original_title": "",
    "release_year": 2021,
    "premiere": "",
    "category": "Tribute",
    "description": "Dawn Porter's uplifting short film examines how the art world responded to the death of Breonna Taylor by using art not only as a form of protest, but as a space to heal.",
    "screening_date": "Saturday, April 18",
    "screening_start_time": "10:00 AM",
    "screening_end_time": "12:00 PM",
    "venue": "Cinema 3",
    "schedule_color": "tan"
  },
  {
    "id": "buckskin",
    "title": "Buckskin",
    "rating": null,
    "original_title": "",
    "release_year": 2026,
    "premiere": "",
    "category": "NEW DOCS",
    "description": "An experimental portrait of the filmmaker's grandfather, Carroll B. Williams Jr., a ground-breaking African-American forester, that reflects on his work and legacy in the twilight of his life.",
    "screening_date": "Friday, April 17",
    "screening_start_time": "1:00 PM",
    "screening_end_time": "3:00 PM",
    "venue": "Cinema 1",
    "schedule_color": "blue"
  },
  {
    "id": "failure-is-a-river-of-mine",
    "title": "Failure Is a River of Mine",
    "rating": null,
    "original_title": "Fracaso es un Rio Mio",
    "release_year": 2026,
    "premiere": "World Premiere",
    "category": "NEW DOCS",
    "description": "Mari is a former rural midwife, Maricielo is a hairdresser, and Iker is a six-year-old boy. Though they appear to share little in common, a gossamer web quietly binds their lives through heartbreak, failure, and unexpected moments of respite.",
    "screening_date": "Saturday, April 18",
    "screening_start_time": "2:30 PM",
    "screening_end_time": "4:30 PM",
    "venue": "Cinema 4",
    "schedule_color": "blue"
  },
  {
    "id": "food-for-everyone-deities-nature-and-humans",
    "title": "Food for Everyone: Deities, Nature and Humans",
    "rating": null,
    "original_title": "Comida para todos: Divinidades, Naturaleza y Humanos",
    "release_year": 2025,
    "premiere": "",
    "category": "NEW DOCS",
    "description": "On an equal footing, voices enter into dialogue with nature. They speak of sustenance, emotional bonds and of how there is no future without a past.",
    "screening_date": "Friday, April 17",
    "screening_start_time": "4:00 PM",
    "screening_end_time": "6:00 PM",
    "venue": "Cinema 1",
    "schedule_color": "blue"
  },
  {
    "id": "ghosts-of-sugar-land",
    "title": "Ghosts of Sugar Land",
    "rating": null,
    "original_title": "",
    "release_year": 2019,
    "premiere": "",
    "category": "Thematic",
    "description": "Shocked when their friend embraces extremism, a group of Muslim Americans in Texas recount their time with him and theories about his fate.",
    "screening_date": "Sunday, April 19",
    "screening_start_time": "10:00 AM",
    "screening_end_time": "12:00 PM",
    "venue": "Cinema 1",
    "schedule_color": "green"
  },
  {
    "id": "gideon-s-army",
    "title": "Gideon's Army",
    "rating": null,
    "original_title": "",
    "release_year": 2012,
    "premiere": "",
    "category": "Tribute",
    "description": "Gideon's Army follows three young, committed public defenders who are dedicated to working for the people society would rather forget. Long hours, low pay, and staggering caseloads are so common that even the most committed often give up.",
    "screening_date": "Thursday, April 16",
    "screening_start_time": "2:00 PM",
    "screening_end_time": "4:00 PM",
    "venue": "Cinema 3",
    "schedule_color": "tan"
  },
  {
    "id": "hair-paper-water",
    "title": "Hair, Paper, Water…",
    "rating": null,
    "original_title": "Tóc, Giấy và Nước…",
    "release_year": 2025,
    "premiere": "",
    "category": "Thematic",
    "description": "Born in a cave and now in her old age, a Rục woman navigates memory and daily life, passing on her disappearing language to her grandchildren.",
    "screening_date": "Thursday, April 16",
    "screening_start_time": "1:00 PM",
    "screening_end_time": "3:00 PM",
    "venue": "Cinema 1",
    "schedule_color": "blue"
  },
  {
    "id": "i-was-born-this-way",
    "title": "I Was Born This Way",
    "rating": null,
    "original_title": "",
    "release_year": 2025,
    "premiere": "",
    "category": "Invited",
    "description": "When Archbishop Carl Bean sang the 1977 disco hit and gay anthem \"I Was Born This Way,\" it was just the start of his mission to create positive change in the world. He went on to found the Minority AIDS Project and the world's first LGBTQ+ church for people of color.",
    "screening_date": "Sunday, April 19",
    "screening_start_time": "5:30 PM",
    "screening_end_time": "7:30 PM",
    "venue": "Fletcher",
    "schedule_color": "yellow"
  },
  {
    "id": "kid-auto-races-at-venice",
    "title": "Kid Auto Races at Venice",
    "rating": null,
    "original_title": "",
    "release_year": 1914,
    "premiere": "",
    "category": "Thematic",
    "description": "Set against the backdrop of a cart competition in California, Charlie Chaplin stars as \"The Tramp\"—a spectator who repeatedly interrupts the race to the increasing frustration of organizers and bystanders.",
    "screening_date": "Saturday, April 18",
    "screening_start_time": "11:00 AM",
    "screening_end_time": "1:00 PM",
    "venue": "Cinema 2",
    "schedule_color": "green"
  },
  {
    "id": "kite",
    "title": "KITE",
    "rating": null,
    "original_title": "Χαρταετός",
    "release_year": 2025,
    "premiere": "North American Premiere",
    "category": "NEW DOCS",
    "description": "Panos, now grown, returns to a childhood ritual—flying a kite with his father, a tradition marking the start of Lent in Greece. But memories are never simple. Sounds and images, fragments of the past, weave together to reconstruct their bond. A documentary about the fragile father-son relationship and the restless power of memory.",
    "screening_date": "Friday, April 17",
    "screening_start_time": "1:00 PM",
    "screening_end_time": "3:00 PM",
    "venue": "Cinema 1",
    "schedule_color": "blue"
  },
  {
    "id": "la-tierra-del-valor-the-home-of-the-brave",
    "title": "La Tierra del Valor (The Home of the Brave)",
    "rating": null,
    "original_title": "",
    "release_year": 2026,
    "premiere": "",
    "category": "NEW DOCS",
    "description": "During a summer of grief and fear brought on by immigration raids in Los Angeles, one small act of bravery gives a community hope.",
    "screening_date": "Saturday, April 18",
    "screening_start_time": "7:00 PM",
    "screening_end_time": "9:00 PM",
    "venue": "Cinema 1",
    "schedule_color": "blue"
  },
  {
    "id": "life-of-an-american-fireman",
    "title": "Life of an American Fireman",
    "rating": null,
    "original_title": "",
    "release_year": 1903,
    "premiere": "",
    "category": "Thematic",
    "description": "One of the earliest American films, this seven-minute short visualizes the rescue of a woman and child, following the fireman who breaks through their bedroom window to bring them to safety.",
    "screening_date": "Saturday, April 18",
    "screening_start_time": "11:00 AM",
    "screening_end_time": "1:00 PM",
    "venue": "Cinema 2",
    "schedule_color": "green"
  },
  {
    "id": "life-without-dreams",
    "title": "Life Without Dreams",
    "rating": null,
    "original_title": "",
    "release_year": 2022,
    "premiere": "",
    "category": "Thematic",
    "description": "Life Without Dreams is set in the outer space of consciousness, where the surfaces of far out planetary bodies form the terrain for an exploration of insomnia and the disappearance of darkness.",
    "screening_date": "Saturday, April 18",
    "screening_start_time": "1:00 PM",
    "screening_end_time": "3:00 PM",
    "venue": "Cinema 1",
    "schedule_color": "blue"
  },
  {
    "id": "man-of-aran",
    "title": "Man of Aran",
    "rating": null,
    "original_title": "",
    "release_year": 1934,
    "premiere": "",
    "category": "Thematic",
    "description": "Stunning location photography and brilliant montage editing build a forceful drama of life on the Aran Islands and islanders' Herculean efforts to survive in unbearably harsh conditions.",
    "screening_date": "Saturday, April 18",
    "screening_start_time": "11:00 AM",
    "screening_end_time": "1:00 PM",
    "venue": "Cinema 2",
    "schedule_color": "green"
  },
  {
    "id": "not-a-pretty-picture",
    "title": "Not a Pretty Picture",
    "rating": null,
    "original_title": "",
    "release_year": 1975,
    "premiere": "",
    "category": "Thematic",
    "description": "A high-stakes experiment in metacinema that broke new ground with its uncompromising examination of date rape, Not a Pretty Picture brings a stunning immediacy to questions about the on-screen representation of sexual violence and the limits of artistic catharsis.",
    "screening_date": "Saturday, April 18",
    "screening_start_time": "1:00 PM",
    "screening_end_time": "3:00 PM",
    "venue": "Cinema 1",
    "schedule_color": "blue"
  },
  {
    "id": "once-you-shall-be-one-of-those-who-lived-long-ago",
    "title": "Once you shall be one of those who lived long ago",
    "rating": null,
    "original_title": "En gång skall du vara en av dem som levat för längesen",
    "release_year": 2025,
    "premiere": "North American Premiere",
    "category": "NEW DOCS",
    "description": "In a small mining town in the north part of Sweden we witness a melancholic, humorous and sometimes absurd last epoch of a place. Personal stories of farewell, change, and the impermanence of life unfold above one of the world's largest underground iron ore mines.",
    "screening_date": "Thursday, April 16",
    "screening_start_time": "7:30 PM",
    "screening_end_time": "9:30 PM",
    "venue": "Cinema 1",
    "schedule_color": "blue"
  },
  {
    "id": "procession",
    "title": "Procession",
    "rating": null,
    "original_title": "",
    "release_year": 2021,
    "premiere": "",
    "category": "Special Presentation",
    "description": "Six men who were sexually abused by Catholic clergy as boys become a makeshift family and find empowerment by creating films inspired by their trauma.",
    "screening_date": "Saturday, April 18",
    "screening_start_time": "7:30 PM",
    "screening_end_time": "9:30 PM",
    "venue": "Cinema 3",
    "schedule_color": "dark_green"
  },
  {
    "id": "punishment-park",
    "title": "Punishment Park",
    "rating": null,
    "original_title": "",
    "release_year": 1971,
    "premiere": "",
    "category": "Thematic",
    "description": "In this harrowing documentary-style fiction film, set during the Nixon presidency, convicted dissidents are offered the choice between life imprisonment and three days in \"Punishment Park\"—a barren, desert landscape where they are pursued by armed forces.",
    "screening_date": "Friday, April 17",
    "screening_start_time": "4:30 PM",
    "screening_end_time": "6:30 PM",
    "venue": "Cinema 3",
    "schedule_color": "blue"
  },
  {
    "id": "remake",
    "title": "Remake",
    "rating": null,
    "original_title": "",
    "release_year": 2025,
    "premiere": "",
    "category": "Invited",
    "description": "For forty years, Ross McElwee has made documentaries which blend autobiography and cultural observation. When his son Adrian died suddenly, the footage he had filmed of his son became something else entirely: a reckoning with what the camera captured, and what it could not. REMAKE traces the fragile bond the camera created between a father and son, and what remains of it now.",
    "screening_date": "Friday, April 17",
    "screening_start_time": "5:00 PM",
    "screening_end_time": "7:00 PM",
    "venue": "Fletcher",
    "schedule_color": "blue"
  },
  {
    "id": "shorts-1",
    "title": "Shorts 1",
    "rating": null,
    "original_title": "",
    "release_year": 2026,
    "premiere": "",
    "category": "NEW DOCS",
    "description": "Program of short films: KITE (dir. Thanos Psichogios); Buckskin (dir. Mars Verrone); Gatorville (dir. Freddie Gluck); The Grandfather Puzzle (dir. Ora DeKornfeld)",
    "screening_date": "Friday, April 17",
    "screening_start_time": "5:00 PM",
    "screening_end_time": "7:00 PM",
    "venue": "Cinema 2",
    "schedule_color": "blue"
  },
  {
    "id": "shorts-2",
    "title": "Shorts 2",
    "rating": null,
    "original_title": "",
    "release_year": 2026,
    "premiere": "",
    "category": "NEW DOCS",
    "description": "Program of short films: No Mean City (dir. Ross McClean); La Tierra del Valor (dir. Cristina Costantini); We Were the Scenery (dir. Christopher Radcliff); BAEA (dir. Terra Long)",
    "screening_date": "Friday, April 17",
    "screening_start_time": "8:00 PM",
    "screening_end_time": "10:00 PM",
    "venue": "Cinema 2",
    "schedule_color": "blue"
  },
  {
    "id": "shorts-3",
    "title": "Shorts 3",
    "rating": null,
    "original_title": "",
    "release_year": 2026,
    "premiere": "",
    "category": "NEW DOCS",
    "description": "Program of short films: The silence of pomegranates (dir. Clara Baj); Food for Everyone: Deities, Nature and Humans (dir. Prin Rodriguez); Mother Lidia (dir. Juan Bautista Tagle & Joaquín Nercasseau); Failure Is a River of Mine (dir. Julia Mendoza Friedman)",
    "screening_date": "Saturday, April 18",
    "screening_start_time": "2:00 PM",
    "screening_end_time": "4:00 PM",
    "venue": "Cinema 2",
    "schedule_color": "blue"
  },
  {
    "id": "shorts-4",
    "title": "Shorts 4",
    "rating": null,
    "original_title": "",
    "release_year": 2026,
    "premiere": "",
    "category": "NEW DOCS",
    "description": "Program of short films: Still Standing (dir. Víctor Tadashi Suarez & Livia Albeck-Ripka); The Cloud Factory (dir. Hannes Lang); an open field (dir. Teboho Edkins)",
    "screening_date": "Sunday, April 19",
    "screening_start_time": "11:00 AM",
    "screening_end_time": "1:00 PM",
    "venue": "Cinema 2",
    "schedule_color": "blue"
  },
  {
    "id": "singing-wings",
    "title": "Singing Wings",
    "rating": null,
    "original_title": "",
    "release_year": 2025,
    "premiere": "",
    "category": "NEW DOCS",
    "description": "Through the intertwined destinies of a wounded stork and an elderly Kurdish woman, whose daughter contemplates migrating to the UK, Singing Wings weaves a poetic parallel between animal and human migration.",
    "screening_date": "Friday, April 17",
    "screening_start_time": "10:00 AM",
    "screening_end_time": "12:00 PM",
    "venue": "Cinema 1",
    "schedule_color": "blue"
  },
  {
    "id": "steal-this-story-please",
    "title": "Steal This Story, Please!",
    "rating": null,
    "original_title": "",
    "release_year": 2025,
    "premiere": "",
    "category": "Invited",
    "description": "Amy Goodman takes on soldiers, politicians, and corporate media in a fearless pursuit of truth.",
    "screening_date": "Thursday, April 16",
    "screening_start_time": "1:30 PM",
    "screening_end_time": "3:30 PM",
    "venue": "Fletcher",
    "schedule_color": "yellow"
  },
  {
    "id": "sunday-encore-1",
    "title": "Sunday Encore 1",
    "rating": null,
    "original_title": "",
    "release_year": 2026,
    "premiere": "",
    "category": "ENCORE",
    "description": "All encore screenings will be announced at 1 p.m. on Sunday, April 19 after the Awards Barbecue concludes.",
    "screening_date": "Sunday, April 19",
    "screening_start_time": "2:00 PM",
    "screening_end_time": "4:00 PM",
    "venue": "Cinema 3",
    "schedule_color": "blue"
  },
  {
    "id": "sunday-encore-2",
    "title": "Sunday Encore 2",
    "rating": null,
    "original_title": "",
    "release_year": 2026,
    "premiere": "",
    "category": "ENCORE",
    "description": "",
    "screening_date": "Sunday, April 19",
    "screening_start_time": "4:30 PM",
    "screening_end_time": "6:30 PM",
    "venue": "Cinema 1",
    "schedule_color": "blue"
  },
  {
    "id": "sunday-encore-3",
    "title": "Sunday Encore 3",
    "rating": null,
    "original_title": "",
    "release_year": 2026,
    "premiere": "",
    "category": "ENCORE",
    "description": "",
    "screening_date": "Sunday, April 19",
    "screening_start_time": "5:00 PM",
    "screening_end_time": "7:00 PM",
    "venue": "Cinema 3",
    "schedule_color": "blue"
  },
  {
    "id": "the-bend-in-the-river",
    "title": "The Bend in the River",
    "rating": null,
    "original_title": "",
    "release_year": 2025,
    "premiere": "",
    "category": "Invited",
    "description": "Following and filming friends for nearly fifty years, The Bend in the River is an exploration of the inexorable flow of aging and the unfinished project of living.",
    "screening_date": "Sunday, April 19",
    "screening_start_time": "11:00 AM",
    "screening_end_time": "1:00 PM",
    "venue": "Fletcher",
    "schedule_color": "yellow"
  },
  {
    "id": "the-cruise",
    "title": "The Cruise",
    "rating": null,
    "original_title": "",
    "release_year": 1998,
    "premiere": "",
    "category": "Thematic",
    "description": "Sailing the streets of Manhattan atop a double-decker bus, Timothy \"Speed\" Levitch waxes philosophical as the city's most eccentric tour guide. Bennett Miller's groundbreaking debut feature captures Speed's bombastic and psychedelic poetry.",
    "screening_date": "Thursday, April 16",
    "screening_start_time": "4:00 PM",
    "screening_end_time": "6:00 PM",
    "venue": "Cinema 1",
    "schedule_color": "green"
  },
  {
    "id": "the-lady-bird-diaries",
    "title": "The Lady Bird Diaries",
    "rating": null,
    "original_title": "",
    "release_year": 2022,
    "premiere": "",
    "category": "Tribute",
    "description": "The Lady Bird Diaries is a groundbreaking documentary film about one of the most influential and least understood First Ladies in history, Lady Bird Johnson, told in her own words from 123 hours of her riveting audio diaries.",
    "screening_date": "Sunday, April 19",
    "screening_start_time": "10:30 AM",
    "screening_end_time": "12:30 PM",
    "venue": "Cinema 3",
    "schedule_color": "tan"
  },
  {
    "id": "there-are-no-words",
    "title": "There Are No Words",
    "rating": null,
    "original_title": "",
    "release_year": 2025,
    "premiere": "",
    "category": "NEW DOCS",
    "description": "Over 40 years ago, filmmaker Min Sook Lee's mother died by suicide. Using her camera, Lee explores long-held silences, unstable memories and unforgettable truths, attempting to understand what happened.",
    "screening_date": "Friday, April 17",
    "screening_start_time": "2:30 PM",
    "screening_end_time": "4:30 PM",
    "venue": "Cinema 4",
    "schedule_color": "blue"
  },
  {
    "id": "time-and-water",
    "title": "Time and Water",
    "rating": null,
    "original_title": "",
    "release_year": 2026,
    "premiere": "",
    "category": "Invited",
    "description": "Facing the death of his country's glaciers and the loss of his beloved grandparents, Icelandic writer Andri Snær Magnason turns his archives into a time capsule to hold what is slipping away — family, memory, time and water.",
    "screening_date": "Sunday, April 19",
    "screening_start_time": "2:30 PM",
    "screening_end_time": "4:30 PM",
    "venue": "Fletcher",
    "schedule_color": "yellow"
  },
  {
    "id": "we-are-pat",
    "title": "We Are Pat",
    "rating": null,
    "original_title": "",
    "release_year": 2025,
    "premiere": "",
    "category": "Invited",
    "description": "We Are Pat is a tale of obsession, transness and how art ages over time told through the thick spectacles of the 1990s cult character Pat from Saturday Night Live.",
    "screening_date": "Saturday, April 18",
    "screening_start_time": "8:30 PM",
    "screening_end_time": "10:30 PM",
    "venue": "Cinema 4",
    "schedule_color": "blue"
  },
  {
    "id": "whispers-in-may",
    "title": "Whispers in May",
    "rating": null,
    "original_title": "Chun Ri Huan You",
    "release_year": 2026,
    "premiere": "North American Premiere",
    "category": "NEW DOCS",
    "description": "In the remote Liangshan Mountains, 14-year-old Qihuo and her friends set out to find a skirt for her rite of passage. What begins as a small quest drifts into a suspended space of childhood, where time slows and the world is vast.",
    "screening_date": "Friday, April 17",
    "screening_start_time": "5:30 PM",
    "screening_end_time": "7:30 PM",
    "venue": "Cinema 4",
    "schedule_color": "blue"
  }
];
